### ISSUE TITLE
Hyper.js freezes after performing search

### ISSUE THREAD

**Issue by pjeziorowski** [jaanauati/hyper-search#59] opened 2019-05-24 23:04 UTC
Entire application freezes after trying to perform a search. 

Environment:
macOS 10.14.5

Hyper.js -->
Renderers: WebGL
Plugins: 
  hyperterm-atom-dark (1.1.2),
  hyper-font-ligatures (0.0.7),
  hyperterm-paste (1.1.2),
  hypercwd (1.4.0),
  hyper-pane (2.1.4),
  hyper-highlight-active-pane (0.1.0),
  hyper-savetext (1.1.1),
  hyper-search (0.2.1)

**Comment by yanirz** [comment] 2019-06-04 13:23
Fixed in #61 (not merged yet)
Please confirm if it's fixed for you

**Comment by jaanauati** [comment] 2019-07-04 20:05
@pjeziorowski as @yanir3 mentioned a fix for this was published ~ 30 days ago; im closing this ticket out, feel free to reopen if the issue is still happening for u.
thanks.

**Closed as completed** 2019-07-04 20:05 UTC

**Comment by pjeziorowski** [comment] 2019-07-20 15:04
Thank you, the solution fixed the problem.
